import { BoyData, GirlData } from '@/interface/data'

export const boyRows: BoyData[] = [
  {
    id: 1,
    date: '2020-05-27',
    sleep: '11.45(不要打我)',
    finish: '这个完成啦，嘻嘻',
    readed: '这个也完成了，嘻嘻（看的是自控力）',
    running: '5.3KM',
    smile: true,
    mustSleep: true,
    checkCoverQuiet: true,
    story: '因为酸奶见到了娇，开心日常的一天~~',
  },
  {
    id: 2,
    date: '2020-05-27',
    sleep: '11.45(不要打我)',
    finish: '这个完成啦，嘻嘻',
    readed: '这个也完成了，嘻嘻（看的是自控力）',
    running: '5.3KM',
    smile: true,
    mustSleep: true,
    checkCoverQuiet: true,
    story: '因为酸奶见到了娇，开心日常的一天~~',
  },
  {
    id: 3,
    date: '2020-05-27',
    sleep: '11.45(不要打我)',
    finish: '这个完成啦，嘻嘻',
    readed: '这个也完成了，嘻嘻（看的是自控力）',
    running: '5.3KM',
    smile: true,
    mustSleep: true,
    checkCoverQuiet: true,
    story: '因为酸奶见到了娇，开心日常的一天~~',
  },
]

export const girlRows: GirlData[] = [{
  id: 1,
  date: '2020-05-27',
  sleep: '11.45(不要打我)',
  finish: '这个完成啦，嘻嘻',
  yoga: true,
  swimming: true,
  coverQuiet: true,
  happy: true,
  company: '陪了，有见面～❤️❤️',
  story: '因为酸奶见到了娇，开心日常的一天~~',
}, {
  id: 2,
  date: '2020-05-27',
  sleep: '11.45(不要打我)',
  finish: '这个完成啦，嘻嘻',
  yoga: true,
  swimming: true,
  coverQuiet: true,
  happy: true,
  company: '陪了，有见面～❤️❤️',
  story: '因为酸奶见到了娇，开心日常的一天~~',
}, {
  id: 3,
  date: '2020-05-27',
  sleep: '11.45(不要打我)',
  finish: '这个完成啦，嘻嘻',
  yoga: true,
  swimming: true,
  coverQuiet: true,
  happy: true,
  company: '陪了，有见面～❤️❤️',
  story: '因为酸奶见到了娇，开心日常的一天~~',
}]
