import { BoyData, GirlData } from '@/interface/data'

export const boyRows: BoyData[] = [
  {
    id: 1,
    date: '2020-05-27',
    sleep: '11.45(不要打我)',
    finish: '这个完成啦，嘻嘻',
    readed: '这个也完成了，嘻嘻（看的是自控力）',
    running: '5.3KM',
    smile: true,
    mustSleep: true,
    checkCoverQuiet: true,
    story: '因为酸奶见到了娇，开心日常的一天~~',
  },
  {
    id: 2,
    date: '2020-05-27',
    sleep: '11.45(不要打我)',
    finish: '这个完成啦，嘻嘻',
    readed: '这个也完成了，嘻嘻（看的是自控力）',
    running: '5.3KM',
    smile: true,
    mustSleep: true,
    checkCoverQuiet: true,
    story: '因为酸奶见到了娇，开心日常的一天~~',
  },
  {
    id: 3,
    date: '2020-05-27',
    sleep: '11.45(不要打我)',
    finish: '这个完成啦，嘻嘻',
    readed: '这个也完成了，嘻嘻（看的是自控力）',
    running: '5.3KM',
    smile: true,
    mustSleep: true,
    checkCoverQuiet: true,
    story: '因为酸奶见到了娇，开心日常的一天~~',
  },
]

export const girlRows: GirlData[] = [{
  id: 1,
  date: '2020-05-27',
  sleep: '11.45(不要打我)',
  finish: '这个完成啦，嘻嘻',
  yoga: true,
  swimming: true,
  coverQuiet: true,
  smile: true,
  company: '陪了，有见面～❤️❤️',
  story: '下午杰给我点了水果茶，很开心～今天下班也很晚，一路小跑回来的。想着跟杰说要尽量好好吃饭好好睡觉，所以回来就去洗澡了，想着收拾完睡前聊一会儿……洗完澡回来，收到了晚安，好吧，应该是不太想聊或者累了。那……晚安了，有点失落呢 “温度”有点低',
}, {
  id: 2,
  date: '2020-05-27',
  sleep: '11.45(不要打我)',
  finish: '这个完成啦，嘻嘻',
  yoga: true,
  swimming: true,
  coverQuiet: true,
  smile: true,
  company: '陪了，有见面～❤️❤️',
  story: '下午杰给我点了水果茶，很开心～今天下班也很晚，一路小跑回来的。想着跟杰说要尽量好好吃饭好好睡觉，所以回来就去洗澡了，想着收拾完睡前聊一会儿……洗完澡回来，收到了晚安，好吧，应该是不太想聊或者累了。那……晚安了，有点失落呢 “温度”有点低',
}, {
  id: 3,
  date: '2020-05-27',
  sleep: '11.45(不要打我)',
  finish: '这个完成啦，嘻嘻',
  yoga: true,
  swimming: true,
  coverQuiet: true,
  smile: true,
  company: '陪了，有见面～❤️❤️',
  story: '下午杰给我点了水果茶，很开心～今天下班也很晚，一路小跑回来的。想着跟杰说要尽量好好吃饭好好睡觉，所以回来就去洗澡了，想着收拾完睡前聊一会儿……洗完澡回来，收到了晚安，好吧，应该是不太想聊或者累了。那……晚安了，有点失落呢 “温度”有点低',
}]
